backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Ürünler"
    folder: "content/products"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Ürün Adı", name: "title", widget: "string"}
      - {label: "Fiyat", name: "price", widget: "string"}
      - {label: "Görsel", name: "image", widget: "image"}
      - {label: "Shopier Linki", name: "shopier_url", widget: "string"}
