backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Ürünler"
    folder: "content/products"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Ürün Adı", name: "title", widget: "string"}
      - {label: "Kategori", name: "category", widget: "select", options: ["Omuz Çantası", "El Çantası"]}
      - {label: "Fiyat", name: "price", widget: "string"}
      - {label: "İndirimli Fiyat", name: "discount_price", widget: "string", required: false}
      - {label: "Ürün Görseli", name: "image", widget: "image"}
      - {label: "Shopier Linki", name: "shopier_url", widget: "string"}

      - {label: "Stokta Var mı?", name: "in_stock", widget: "boolean", default: true}
