backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Çantalar"
    file: "products.json"
    fields:
      - { label: "Ürün Adı", name: "title", widget: "string" }
      - { label: "Fiyat", name: "price", widget: "number" }
      - { label: "Görsel", name: "image", widget: "image" }